### PR TITLE
Fetching feeds

### PR DESCRIPTION
**Pull request by HansJesse**
1. Add setupTheme to DiscoverActivity
2. Add column for storing last fetch datetime per feed to stop the reappearing feeds.  This seems to have fixed the issue for me, but don't merge if you are opposed to the database/logic change.
3. Optimize the filtering by including in the sequence filter and using a HashSet to eliminate duplicates.

### CODE REVIEW

**Comment by HansJesse** [comment]
Saw an old entry reappear.  Closing this until I determine why.

**Comment by kitlith** [comment]
Did you ever figure out why this didn't work?

**Comment by hansjessebv** [comment]
No, haven't had time to continue looking into this unfortunately.

**Comment by FredJul** [comment]
From what I know, old entries can reappear if the rss/atom feed provides an invalid date (at least one that rome-opml doesn't parse) or if the old entry has been modified in the feed (with an updated modification date)

**Pull request closed without merging**
