### PR TITLE
Update Indonesian translation

### PR DESCRIPTION
**Pull request by zmni**

### CODE REVIEW

**Comment by FredJul** [comment]
Hi, you may didn't noticed it but I have setup a webpage to edit translations on https://frju.crowdin.com/flym

Could you please try to do your changes there? I believe it will be a lot easier for you in the future.

Regards,
Fred

**Comment by zmni** [comment]
Oh didn't know that. Thanks.

I have account on crowdin (`zmni`), but I can't login, can you help me?

**Comment by FredJul** [comment]
I have used the need version of crowdin (still in beta) and I believe you need to create a new account on it (could be the same login/pass as previously)

**Comment by zmni** [comment]
It's done. Thank you.

**Pull request closed without merging**
