### PR TITLE
Feature/improve filters

### PR DESCRIPTION
**Pull request by CodingSpiderFox**

### CODE REVIEW

**Comment by CodingSpiderFox** [comment]
solves #359

**Comment by CodingSpiderFox** [comment]
*ping*

**Comment by FredJul** [comment]
First of all, sorry for the late answer.

To be honest, I'm not sure to understand your PR and can't merge it as it is.
1/ technically, there is several things that I dislike like the use of minApi 26, AsyncTasks. Also, some of my comments from #361 are again applicable here
2/ I actually don't understand the purpose of all this. Could you explain it more? I particularly don't understand why there is now two settings. Do there really need to be in DB? Can't they be in sharedPref like today?

**Comment by CodingSpiderFox** [comment]
1) Unfortunately, I don't have time at the moment to put further effort into it. Maybe when the cold winter days arrive.
2) You're right, I think there was a reason for that when I started implementing it but I don't remember

**Comment by FredJul** [comment]
no problem, but for now i'm closing this PR until this is answers to theses questions

**Pull request closed without merging**
