### PR TITLE
Add setting to automatically refresh all feeds on startup

### PR DESCRIPTION
**Pull request by amkcpu**
When checked, this automatically refreshes all feeds on startup.

### CODE REVIEW

**Comment by FredJul** [comment]
Thanks, I know this has been asked by some people so thank you for your help

**Comment by amkcpu** [comment]
No problem, thanks for the great app!

**Comment by FredJul** [comment]
I actually did some code improvement on it (I believe it was not perfectly working). You can see them in the last commit

**Comment by amkcpu** [comment]
This fixes #381 and #338 right?

**Comment by amkcpu** [comment]
Maybe to make the issue described in #381 clearer, "Enable automatic refresh" could be rename to something like "Refresh feeds in background" or "Schedule automatic refresh in background".
If you want, I can make another pull request to do that.

**Pull request merged**
