### PR TITLE
Updated zh (Chinese) translation

### PR DESCRIPTION
**Pull request by linsui**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by FredJul** [comment]
I'm sorry but these modifications are actually not good enough to be merged:
- there is several string deletion (certainly due to the use of Stringlate)
- this is in conflict with several strings that has been translated meanwhile

So while I appreciate your help, I cannot merge it as it is. Moreover I'm not skilled enough in chinese to know myself what string I should pick. Is it possible for you to redo the translations without Stringlate?

**Comment by linsui** [comment]
Of course. I find that there is no `<item quantity="one">` in values-zh/strings.xml now. Should I add it? And could I change some strings to add space between English and Chinese and fix some other problems?

**Comment by linsui** [comment]
I have discussed [here](https://github.com/FredJul/Flym/commit/0507023d88e8261bb990aea33a0b172cc5a997cf#commitcomment-30889987) with @BLumia and we think it would be better to translate all 'feed' to '订阅源‘ and all 'item' and 'entry' to '文章‘. But I can't find another translator Stefan Handschuh. So could I change the translation?

**Comment by BLumia** [comment]
> But I can't find another translator.

@linsui If you are not familiar with how git works, you can edit this file on GitHub directly by click the **Edit** button on [this page](https://github.com/FredJul/Flym/blob/master/app/src/main/res/values-zh/strings.xml). After you commit your changes, you can then submit a Pull Request :)

**Comment by FredJul** [comment]
Well, on my side I do not speak Chinese at all, so I trust you :)

**Pull request closed without merging**
