### PR TITLE
Discover feeds

### PR DESCRIPTION
**Pull request by HansJesse**
This is a bit of a UX change, but I am hoping this will be a starting point to improve feed discovery and searching.  Please review, try it out, and stay in touch.  I'm happy to help if I can. Cheers!

### CODE REVIEW

**Comment by FredJul** [comment]
Hi,

Sorry for the delay I needed some times to test and review your PR. Overall I have to say that it's a great improvement over the previous version! Thank you!

There is some things that I dislike in the code (like different indentation, unused imports, permissions at the end of the manifest, use of Java-like mXXX private variable naming, use of runInUiThread instead of anko's uiThread, ...) but nothing really blocking and the code wasn't perfect before as well. So I accept to merge this PR and I guess I will do some few modifications afterward.

In the futur I encourage you to check the "Optimize Import" and "Reformat code" options when you commit the files in Android Studio.

But again, thank you a lot!

**Comment by HansJesse** [comment]
Thanks for the feedback! Please feel free to leave inline comments in future PRs.  The feedback is an opportunity to improve my Kotlin. Thanks!

**Comment by ildar** [comment]
I just tested it (I know, too late) and sorry, I don't like it.
1. The feed validation is gone. The feed is added and then never shows
items.
2. The invalid feed from (1) never gets RED as invalid on update.
3. The above reminds me the feed discovery we had in Flym v.1. That was
supa-cool. No such thing in v.2 :-(

**Comment by ildar** [comment]
re-triage?

**Pull request merged**
